### ISSUE TITLE
The prospects of the project

### ISSUE THREAD

**Issue by eugenpar** [aresio/fst-pso#16]
Hi, Marco! What are the prospects for seeing the project in Python 3? Evgeniy

**Comment by aresio** [comment]
Hi! FST-PSO is already compatible with Python 3, we ported the code one year ago.

**Comment by eugenpar** [comment]
Programs at https://github.com/aresio/fst-pso written for Python 2:print statement without parentheses. Perhaps there is another library?

**Comment by aresio** [comment]
Hi, I apologize, that was an outdated example. 

I can confirm that the library is 100% compatible with Python 3. We have been using and developing only with Python 3 in the last 18 months.

All the best, 

Marco
