### ISSUE TITLE
Error in training_NN.py

### ISSUE THREAD

**Issue by eugenpar** [aresio/fst-pso#17]
Hello, Marco! Is it possible to get an explanation of the reason for the error in the 862 module statement fstpso.py at startup training_NN.py:
"ERROR: the specified function does not seem to implement a correct fitness function"
Evgeniy

**Comment by aresio** [comment]
Hi, 

I am sorry, the parallel interface still tries to test the fitness function before using it. Please disable that feature by setting skip_test=True.

That is, replace line 122:

FSTPSO.set_parallel_fitness(f, arguments={'x': data.data, 'y': data.target })

with the following:

FSTPSO.set_parallel_fitness(f, arguments={'x': data.data, 'y': data.target }, skip_test=True)

This should work. I will fix the parallel interface asap.

Thank you for pointing out the error!

Marco

**Comment by aresio** [comment]
Evgeniy, please update to the last version of FST-PSO asap! I am closing this issue, should be fixed now.

**Comment by eugenpar** [comment]
OK!
