### ISSUE TITLE
maximize objective function instead of minimizing

### ISSUE THREAD

**Issue by saeedsltm** [aresio/fst-pso#18]
Dear @aresio, Is it possible to set a parameter in FST-PSO for maximizing a fitness function instead of minimizing it? In my case i'm trying to maximize an objective function to get improvement of each new particle, so i'm using weighted average which is a positive gradually function.

**Comment by aresio** [comment]
Hi Saeed,

You can convert a maximisation problem to a minimisation by changing the sign of the fitness function, e.g.:

```
def fitness(particle):
    #calculate things
    return fitness
```

would become

```
def fitness(particle):
    #calculate things
    return -fitness
```

Please let me know if that works for you!

**Comment by saeedsltm** [comment]
Dear @aresio Thanks.
