### ISSUE TITLE
Running FST-PSO using GPU

### ISSUE THREAD

**Issue by saeedsltm** [aresio/fst-pso#19]
Dear @aresio , I'm trying to use FST-PSO with GPU in parallels mode, so i wrote the following script:

```
from numba import jit
from numba.typed import List
import numpy as np
from timeit import default_timer as timer
from fstpso import FuzzyPSO	

@jit()
def objective_f(x):
    return x**2

@jit()
def example_fitness1(particle):
    r = 0
    for i in particle:
        r+=objective_f(i)
    return r
    # return sum(map(objective_f, particle))

@jit()
def example_fitness2(particles):
    r = []
    for p in particles:
        r.append(example_fitness1(p))
    return r
    # return list(map(example_fitness1, particles))

if __name__ == '__main__':
    # Without GPU
    start = timer()
    dims = 10
    FP = FuzzyPSO()
    limits = np.array([[-10, 10]]*dims, dtype=np.float64)
    FP.set_search_space(limits)	
    FP.set_fitness(example_fitness1, skip_test=True)
    result =  FP.solve_with_fstpso()
    t1 = timer()-start
    # With GPU
    start = timer()
    FP = FuzzyPSO()
    FP.set_search_space(limits)
    FP.set_parallel_fitness(example_fitness2, skip_test=True)
    result =  FP.solve_with_fstpso()
    t2 = timer()-start
    print("without GPU:", t1)
    print("with GPU:", t2)
```

The code will be run successfully without any error. but in GPU mode, it is not running in "nopython" mode which is the most efficient way. The warnings says something related to not having a fixed type format of inputs. Could you please take a look at it? It'll be really appreciated if you could send me a simple application of FST-PSO in GPU mode.

**Comment by aresio** [comment]
Hi,

I am not familiar with Numba, so I need to learn a bit about its functioning. 

I read on StackOverlow that Numba does not support list of lists as inputs to functions in nopython mode, which might be the case for the parallel fitness (the argument "particles" is indeed a list of lists). I will investigate.

**Comment by saeedsltm** [comment]
Dear @aresio Yes, exactly that's the case, do you thinks its possible to convert list to numpy array in FST-PSO? I did take a look at the source code and find it out all parts are designed based on python list, but converting them to array may cause getting improvement in its efficiency.

**Comment by aresio** [comment]
Yes, that's indeed something I would like to implement in the near future, there will be a massive refactoring of FST-PSO in the next weeks. I will try priotize this functionality, so that you can run your tests.

**Comment by saeedsltm** [comment]
@aresio Great news. thanks :)
