### ISSUE TITLE
fstpso for multi-modal functions

### ISSUE THREAD

**Issue by UKonge** [aresio/fst-pso#3]
As stated in README.md, fstpso can be used to find multiple minimas for a multi-modal function. Can you please tell me how to use this feature?
Thanks.

**Comment by aresio** [comment]
HI, 

fst-pso can deal with multi-modal functions but it is not designed to return multiple minimas. Still you can, in principle, collect the local best positions saved by the particles and get some information about the local minima in the search space. 

These data can be extracted from the FuzzyPSO object; I provide a simple example to print such information:

```
FP = FuzzyPSO()
...
FP.solve_with_fstpso()
...
for solution in FP.Solutions:
  print solution.B
```
