### ISSUE TITLE
Parameters generated outside of boundaries when domain is small

### ISSUE THREAD

**Issue by CharlyEmpereurmot** [aresio/fst-pso#5]
Hello Marco,

First, thank you very much for FST-PSO :+1: This is inspiring.

I'm trying to generate CG models automatically for molecular/atomistic data and I have search space boundaries that can be small numbers, i.e. ranging between approximately [ 0.2 , 0.5 ]. I noticed the very first step generated parameters outside of the boundaries, here is the log:

```
 * Max distance: 42640.428000
 * Search space boundaries set to: [[0.358, 0.383], [0.293, 0.303], [0.318, 0.403], [0.268, 0.278], [0.343, 0.418], [0.313, 0.372], [0.287, 0.368], [2000, 18000], [2000, 18000], [2000, 18000], [2000, 18000], [2000, 18000], [2000, 18000], [2000, 18000], [80.0, 120.0], [72.0, 112.0], [132.0, 174.0], [90.0, 108.0], [156.0, 178.0], [156.0, 178.0], [64.0, 178.0], [116.0, 178.0], [2, 1800], [2, 1800], [2, 1800], [2, 1800], [2, 1800], [2, 1800], [2, 1800], [2, 1800], [-10.0, 10.0], [-32.0, 26.0], [2, 400], [2, 400]]
 * Max velocities set to: [0.025000000000000022, 0.010000000000000009, 0.08500000000000002, 0.010000000000000009, 0.07499999999999996, 0.059, 0.08100000000000002, 16000.0, 16000.0, 16000.0, 16000.0, 16000.0, 16000.0, 16000.0, 40.0, 40.0, 42.0, 18.0, 22.0, 22.0, 114.0, 62.0, 1798.0, 1798.0, 1798.0, 1798.0, 1798.0, 1798.0, 1798.0, 1798.0, 20.0, 58.0, 398.0, 398.0]
 * Number of particles automatically set to 21
 * Testing fitness evaluation

FITNESS EVAL NB: 1
parameters_set: **[1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10, 1e-10]**
```

I have not figured out yet where does this come from. Then, the 2nd step was OK:

```
FITNESS EVAL NB: 2
parameters_set: **[0.3782247712370728, 0.29471002480023945, 0.32822344843076917, 0.27495027426026036, 0.39557766666708927, 0.31374108474673484, 0.31994828915385143, 14324.049664364093, 13631.219158853737, 6977.469487847179, 3392.128481837204, 9958.798593840409, 10588.042118089557, 7987.300537173034, 84.81749922794796, 102.80782255881545, 137.93908532586582, 90.2234656283203, 170.88326998615284, 169.09300906256658, 117.98540044553707, 174.73879850965767, 1468.187099744174, 1114.142792303141, 1247.43720219181, 783.7690041528026, 1574.2966551268116, 1031.441616458798, 1530.5229208332867, 1070.7841646004197, -1.5559937813395095, -29.971529833192434, 106.86410445743009, 373.52579168916037]**
```

Also, would you be kind enough to confirm FST-PSO should indeed be the right tool to optimize high-dimensional black-box single objective functions that are not very expensive (3-10 minutes per iteration on the machine I have at hand) ? Depending on my systems, I typically have between 40 and 200 dimensions for which the domains can be one of these three: [ 0.2 , 0.5 ] or [ 10 , 400 ] or [ 1k , 20k ]. I can do between 500 and 1500 iterations a day and each problem is worth solving in ~ 3 days.

Thank you very much in advance for any help you can provide ! :100:

**Comment by aresio** [comment]
Hello Charly! Thank your interest in FST-PSO!

It is actually weird, FST-PSO should not generate individuals outside the boundaries of the search space. It might be possible, though, that the initial parameterization that you see is just the dummy vector that FST-PSO uses to self-test the fitness function, at the beginning of the optimization. You can verify this theory by adding the optional argument 

`skip_test = True `

when you call the set_fitness() method. If you no longer see a wrong parameterization, it was that :) 

Considering your second question, FST-PSO was actually designed to optimize high-dimensional black-box single-objective functions. 40-200 dimensions is okay, in our tests FST-PSO performed well. Beyond that you might want some alternative decomposition-based algorithm for large-scale optimization.  If you want to reduce the running time of the optimization, you can consider distributing your fitness evaluations over multiple processors and leverage FST-PSO's facilities for parallel fitness evaluation. Let me know if I can help you with that :)

**Comment by CharlyEmpereurmot** [comment]
Hello Marco,

That was indeed due to the dummy vector for testing the fitness function :) Everything works just fine.

At the moment FST-PSO can handle my optimization needs perfectly within 1-3 days even for systems that I would call complicated, among the ones I'm currently interested into. I use 8 to 16 cores + 1 GPU for my serial black-box objective evaluation and that is OK, I do not feel the need to make this faster at the moment. I believe I need to improve the calculation of my objective function first (i.e. the float to be minimized, that is calculated from the output of my black-box, still too noisy simulation) and there will be some performance gain there.

Thank you very much for your invaluable help :+1:
