### ISSUE TITLE
Feeding 1+ initial guesses

### ISSUE THREAD

**Issue by CharlyEmpereurmot** [aresio/fst-pso#6]
Hello Marco,

I know this is not always useful depending on how the optimization problem is framed, but it could be super nice to be able to feed 1 or more initial guesses of the parameters during the initialization of the swarm (i.e. set a few particles with user defined values). I believe there are few algorithms that allow to do this, while this is sometimes super useful and time saving !

I could try to modify the code myself to begin with. Do you think this should be straightforward, or should I pay attention to specific stuff ?

Thank you very much in advance :+1:

**Comment by aresio** [comment]
Hi Charly! That would be an interesting and useful feature. I am implementing that functionality, it will be available in the next version of FST-PSO.

**Comment by CharlyEmpereurmot** [comment]
That is great ! :100:

**Comment by aresio** [comment]
Hi Charly,
as promised I just uploaded FST-PSO v1.5 which introduces the support for the initial guesses. You can provide FST-PSO with a list/array of initial guesses by using the new optional argument `initial_guess_list=[ [guess1], [guess2] ...]` of the `solve_with_fstpso()` method. Please note that the number of guesses must be smaller than the number of particles in the swarm. 

Please let me know if everything works as you expected!

**Comment by CharlyEmpereurmot** [comment]
It works like a charm and gives the results I expected :+1: Thank you!

As a side note, at first I had mistakenly initialized the swarm with an initial guess that had a value outside of the search space for a given dimension. I had no errors or bugs that made the script stop. So it was proceeding ... but probably not in a good way. It would be nice to check for this kind of human mistakes!

**Comment by aresio** [comment]
Good point, I will add that feature in the next release!
